### ISSUE TITLE
Downloading stuck at middle 

### ISSUE THREAD

**Issue by eddygrant000** [mariosemes/PornHub-downloader-python#12]
I was trying to download a playlist. but it's automatically stuck after 2 or 3 videos
nothing happened. I have to terminate my script and restart again & again.
and one more thing please tell me 
could we increase downloading speed BCS maximum speed using by this script 1.5 MB/ps

![Screenshot from 2020-03-26 19-42-32](https://user-images.githubusercontent.com/45393031/77656504-fb004600-6f99-11ea-8023-750697a539af.png)

**Comment by mariosemes** [comment]
1. Sometimes youtube-dl takes a while to do its job. It looks like its stuck, but you just need to wait.
2. The download spead depends on the ph host, ph account location and so on. Its not script or youtube-dl oriented.
