### ISSUE TITLE
playlist only can down first 36 items'

### ISSUE THREAD

**Issue by cnmstudio** [mariosemes/PornHub-downloader-python#13]
i updated the youtube-dl and every playlist can only download the first 36 videos

**Comment by mariosemes** [comment]
There seems to a new problem from PH causing this. Playlists are loaded with lazyload on the page, so the first 36 videos are loaded, and the rest is loaded with jquery I think.

The guys at youtube-dl should check it out.

**Comment by benjamincoven** [comment]
Hi, someone found a workaround on youtube-dl [here](https://github.com/ytdl-org/youtube-dl/issues/22824#issuecomment-599147721).

Got this error on the script:
`Database exists.
PornHub url validated.
This is a PLAYLIST url,
and the URL is existing.
Traceback (most recent call last):
  File "phdler.py", line 55, in <module>
    main()
  File "phdler.py", line 21, in main
    add_check(sys.argv[2])
  File "/home/pi/phdl/PornHub-downloader-python/functions.py", line 87, in add_check
    add_item(name_check)
  File "/home/pi/phdl/PornHub-downloader-python/functions.py", line 271, in add_item
    item_name = get_item_name(item_type, name_check)
  File "/home/pi/phdl/PornHub-downloader-python/functions.py", line 110, in get_item_name
    title = finder.find(id='watchPlaylist').text.replace('\n','').strip()
AttributeError: 'NoneType' object has no attribute 'find'`

I can try to debug it but if you have any tips it would be great.

Thanks
