### ISSUE TITLE
Type pornstar does not work

### ISSUE THREAD

**Issue by homelabtest** [mariosemes/PornHub-downloader-python#16]
It seems as if not all types work well. As type model and single video files work correctly, the type pornstar doesn't. Nothing happens if there is added a correct link and then started the program. Why does this not work? 

[phdl-log.txt](https://github.com/mariosemes/PornHub-downloader-python/files/4639357/phdl-log.txt)

**Comment by mariosemes** [comment]
Should be fixed with the latest push.
