### ISSUE TITLE
Adding a list will only find the latest 36 videos in that list.

### ISSUE THREAD

**Issue by chrlet** [mariosemes/PornHub-downloader-python#17]
Basically what the title says, If there are more than 36 videos in a list the older ones will not be found and downloaded.

**Comment by leightonstarwalt** [comment]
I've noticed the same problem. When downloading a given playlist, the script only downloads and parses the first page, which results in only the first 36 items being downloaded. It's effectively ignoring the other pages, or just doesn't know to check if other pages for that playlist exist.

**Comment by mariosemes** [comment]
The development of this tools is deprecated.
Feel free to fork it and keep on developing it.
