### ISSUE TITLE
How do i resume my downloads

### ISSUE THREAD

**Issue by roshanconnor123** [mariosemes/PornHub-downloader-python#19]
Hi
I was downloading a huge playlist of around 500 videos and my download got cutoff at 300 videos
Is there any way to resume downloads
Thanks

**Comment by elpscrk** [comment]
XD

**Comment by cardoso-neto** [comment]
Doesn't `python phdler.py start` accomplish exactly that?

**Comment by mariosemes** [comment]
The development of this tools is deprecated.
Feel free to fork it and keep on developing it.

**Comment by cardoso-neto** [comment]
Thank you for the great work.
