### ISSUE TITLE
encode error

### ISSUE THREAD

**Issue by huhao1987** [mariosemes/PornHub-downloader-python#2]
When it try to download the videos, it will return a error message "encode error.........". 
The problem should be happened from the command of youtube-dl, but when I use youtube-dl to download videos directly, it works.

**Comment by dlsyaim** [comment]
pip install --upgrade youtube-dl

**Comment by mariosemes** [comment]
Update your youtube-dl to the latest version = 01-01-2020 and everything should work just fine again.
"pip install --upgrade youtube-dl"
