### ISSUE TITLE
Some sites do not work

### ISSUE THREAD

**Issue by homelabtest** [mariosemes/PornHub-downloader-python#21]
I would like to add https://www.pornhub.com/pornstar/stacy-cruz, but for uncertain reason the program does not add videos for this URL. It looks like she has some specific profile page, simba87 said here: https://github.com/mariosemes/PornHub-downloader-python/issues/18

**Comment by jvazservices** [comment]
This is the difference
The path does not contain videos

https://pt.pornhub.com/pornstar/stacy-cruz?page=2

https://pt.pornhub.com/pornstar/riley-reid/videos?page=4

**Comment by mariosemes** [comment]
The development of this tools is deprecated.
Feel free to fork it and keep on developing it.
