### ISSUE TITLE
cannot dowonload and connect

### ISSUE THREAD

**Issue by duzhiyuanyuan** [mariosemes/PornHub-downloader-python#28]
ConnectionResetError: [WinError 10054]

**Comment by garaouz** [comment]
![94144466_233902414485237_3862809847762249268_n](https://user-images.githubusercontent.com/70749820/92382763-6cc5e980-f10d-11ea-8704-59ec7c3c8dbb.jpg)
![IMG_5520](https://user-images.githubusercontent.com/70749820/92382793-7e0ef600-f10d-11ea-9687-c1d39979855a.JPG)

**Comment by mariosemes** [comment]
The development of this tools is deprecated.
Feel free to fork it and keep on developing it.
