### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by fakartstore** [mariosemes/PornHub-downloader-python#3]
ERROR: Unable to extract encoded url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. [download] Downloading video 5 of 124 [PornHub] ph5d764ab29cbc8: Downloading pc webpage

i was update yt-dl.org but still the same

**Comment by leo1115** [comment]
I am also facing the same issue. Plz help.

**Comment by mariosemes** [comment]
Update your youtube-dl to the latest version = 01-01-2020 and everything should work just fine again.
"pip install --upgrade youtube-dl"
