### ISSUE TITLE
Error on downloading

### ISSUE THREAD

**Issue by dam358** [mariosemes/PornHub-downloader-python#39]
[PornHubUserVideosUpload] Executing JS on webpage
ERROR: Executing JS failed
:qt.qpa.screen: QXcbConnection: Could not connect to display
Could not connect to any X display.
; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

I've tried to update youtube-dl, force a mode without screen .... but I haven't make it work

**Comment by mariosemes** [comment]
The development of this tools is deprecated.
Feel free to fork it and keep on developing it.
