### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'find'

### ISSUE THREAD

**Issue by massivroom** [mariosemes/PornHub-downloader-python#44]
When trying to add to list, I'm getting this error:

AttributeError: 'NoneType' object has no attribute 'find'

Can't add anything. If I try to add batch, I get this error:

PermissionError: [Errno 13] Permission denied: 'D:\\DoWNLoad\\PornHub-downloader-python-master'

**Comment by JoachimFlottorp** [comment]
https://github.com/mariosemes/PornHub-downloader-python/blob/428d8f3fe367987b655e6710090587bd86486f15/functions.py#L94

Remove this line!

**Comment by massivroom** [comment]
Thanks man, this works!
