### ISSUE TITLE
'download folder PATH'

### ISSUE THREAD

**Issue by kklod** [mariosemes/PornHub-downloader-python#53]
How can I change it ? thanks!

**Comment by boivinx7** [comment]
well you got 2 choices my dude, 
1.  is the simpler one: 
Go to the PornHub-downloader-python-master folder and delete database.db
2. is the one you do if you dont want to loose your DB info.
Go install https://sqlitebrowser.org/dl/
Then with that open the database.db under PornHub-downloader-python-master

Go in the Browse Data Tab, select ph_settings Table and there you see the setting and you can change it.

![image](https://user-images.githubusercontent.com/30272385/130526338-2bce3f99-29e6-4e75-ada6-72de19adf881.png)

**Comment by kklod** [comment]
> able and there you see the setting and you can cha

thanks dude!
