### ISSUE TITLE
No error handling/retry

### ISSUE THREAD

**Issue by duck414** [mariosemes/PornHub-downloader-python#8]
The script as written will skip over currently published videos that have failed, update the database to mark that source as scraped, and continue on.

There is no way to retry failed videos outside of manual going back into the database and changing the scrape date.

**Comment by mariosemes** [comment]
The option here is to create a fully selfstanding PH downloaded. TBH, I am not looking forward to do that :)
Thats why we use youtube-dl as the main downloader.

**Comment by mariosemes** [comment]
The development of this tools is deprecated.
Feel free to fork it and keep on developing it.
